version: '3.4'
services:
    nginx:
        container_name: orct2p_nginx
        image: saadbruno/openrct2_plugin_repository_nginx:latest
        build:
            context: ./
            dockerfile: docker/nginx/prod/Dockerfile
        ports:
            - "${HTTP_PORT}:80"
        env_file:
            - .env
        depends_on:
            - php-fpm
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
    php-fpm:
        container_name: orct2p_php-fpm
        image: saadbruno/openrct2_plugin_repository_php:latest
        build:
            context: ./
            dockerfile: docker/php-fpm/prod/Dockerfile
        env_file:
            - .env
        depends_on:
            - mysql
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
    mysql:
        container_name: orct2p_mysql
        image: mysql:8.0.16
        env_file: .env
        volumes:
            - ./docker/mysql/mysql-low-memory.cnf:/etc/mysql/conf.d/mysql-low-memory.cnf:ro
            - ./docker/mysql/orct2p.sql:/docker-entrypoint-initdb.d/orct2p.sql:ro
            - orct2p-db:/var/lib/mysql
        restart: unless-stopped
        logging:
            options:
                max-size: 10m
volumes:
    orct2p-db:
