version: '3.4'
services:
    nginx:
        container_name: orct2p_nginx
        image: nginx:latest
        ports:
            - "${HTTP_PORT}:80"
        volumes:
            - ./code:/var/www/code
            - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/logs:/var/log/nginx
        env_file:
            - .env
        depends_on:
            - php-fpm
        logging:
            options:
                max-size: 10m
    php-fpm:
        container_name: orct2p_php-fpm
        build: ./docker/php-fpm
        image: orct2p_php-fpm_dev:latest
        expose:
            - "9000"
        volumes:
            - ./code:/var/www/code
            - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        env_file:
            - .env
        depends_on:
            - mysql
        logging:
            options:
                max-size: 10m
    mysql:
        container_name: orct2p_mysql
        image: mysql:8.0.16
        expose:
            - "3306"
        volumes:
            - ./mysql-mount:/var/lib/mysql
        env_file: .env
        logging:
            options:
                max-size: 10m
