version: '3.4'
services:
    traefik:
        container_name: orct2p_traefik
        image: traefik:v1.7
        ports:
            - "${HTTP_PORT}:80"
            - "${HTTPS_PORT}:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        build:
            context: .
            dockerfile: ./traefik/prod/Dockerfile
        labels:
            - traefik.backend=traefik
            - traefik.frontend.rule=Host:www.traefik.${DOMAIN_NAME},traefik.${DOMAIN_NAME}
            - traefik.port=8080
        networks:
            - proxy.openrct2plugins
    nginx:
        container_name: orct2p_nginx
        image: nginx:latest
        build:
            context: ../
            dockerfile: docker/nginx/prod/Dockerfile
        labels:
            - traefik.backend=nginx
            - traefik.frontend.rule=Host:www.${DOMAIN_NAME},${DOMAIN_NAME}
            - traefik.port=80
        networks:
            - proxy.openrct2plugins
        env_file:
            - .env
        links:
            - php-fpm
        depends_on:
            - mysql
    php-fpm:
        container_name: orct2p_php-fpm
        build:
            context: ../
            dockerfile: docker/php-fpm/prod/Dockerfile
        expose:
            - "9000"
        labels:
            - traefik.enable=false
        networks:
            - proxy.openrct2plugins
        env_file:
            - .env
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        container_name: orct2p_mysql
        image: mysql:5.7.22
        expose:
            - "3306"
        env_file: .env
        labels:
            - traefik.enable=false
        networks:
            - proxy.openrct2plugins
networks:
    proxy.openrct2plugins:
        driver: overlay
        external: true
        attachable: true