version: '3.4'
services:
    nginx:
        container_name: orct2p_nginx
        image: nginx:latest
        ports:
            - "${HTTP_PORT}:80"
        build:
            context: ../
            dockerfile: docker/nginx/prod/Dockerfile
        networks:
            - proxy.openrct2plugins
        env_file:
            - .env
        links:
            - php-fpm
        depends_on:
            - mysql
    php-fpm:
        container_name: orct2p_php-fpm
        build:
            context: ../
            dockerfile: docker/php-fpm/prod/Dockerfile
        expose:
            - "9000"
        networks:
            - proxy.openrct2plugins
        env_file:
            - .env
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        container_name: orct2p_mysql
        image: mysql:5.7.22
        expose:
            - "3306"
        env_file: .env
        networks:
            - proxy.openrct2plugins
networks:
    proxy.openrct2plugins:
        driver: overlay
        external: true
        attachable: true