# traefik + nginx + php-fpm + mysql + phpmyadmin + portainer
version: '3.4'
services:
    traefik:
        container_name: orct2p_traefik
        image: traefik:v1.7
        ports:
            - "${HTTP_PORT}:80"
            #- "443:443"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml
            - ./traefik/acme:/etc/traefik/acme
        labels:
            - traefik.backend=traefik
            - traefik.frontend.rule=Host:www.traefik.${DOMAIN_NAME},traefik.${DOMAIN_NAME}
            - traefik.port=8080
        networks:
            - proxy.${DOMAIN_NAME}
    nginx:
        container_name: orct2p_nginx
        image: nginx:latest
        volumes:
            - ../code:/var/www/code
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/logs:/var/log/nginx
        labels:
            - traefik.backend=nginx
            - traefik.frontend.rule=Host:www.${DOMAIN_NAME},${DOMAIN_NAME}
            - traefik.port=80
        networks:
            - proxy.${DOMAIN_NAME}
        env_file:
            - .env
        links:
            - php-fpm
        depends_on:
            - mysql
    php-fpm:
        container_name: orct2p_php-fpm
        build: ./php-fpm
        expose:
            - "9000"
        volumes:
            - ../code:/var/www/code
            - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        labels:
            - traefik.enable=false
        networks:
            - proxy.${DOMAIN_NAME}
        env_file:
            - .env
        links:
            - mysql
        depends_on:
            - mysql
    mysql:
        container_name: orct2p_mysql
        image: mysql:5.7.22
        expose:
            - "3306"
        volumes:
            - ../mysql:/var/lib/mysql
        env_file: ./mysql/.env
        labels:
            - traefik.enable=false
        networks:
            - proxy.${DOMAIN_NAME}
    phpmyadmin:
        container_name: orct2p_phpmyadmin
        image: phpmyadmin/phpmyadmin
        labels:
            - traefik.backend=pma
            - traefik.frontend.rule=Host:www.pma.${DOMAIN_NAME},pma.${DOMAIN_NAME}
            - traefik.port=80
        environment:
            PMA_HOST: mysql
        networks:
             - proxy.${DOMAIN_NAME}
        links:
            - mysql
        depends_on:
            - mysql
    portainer:
        container_name: orct2p_portainer
        image: portainer/portainer
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./portainer:/data
        labels:
            - traefik.backend=portainer
            - traefik.frontend.rule=Host:www.portainer.${DOMAIN_NAME},portainer.${DOMAIN_NAME}
            - traefik.port=9000
        networks:
             - proxy.${DOMAIN_NAME}
networks:
    proxy.openrct2plugins.test:
        driver: overlay
        external: true
        attachable: true